"""🔬 Research Agent (GPT Researcher style)

Based on GPT Researcher's deep research capabilities.
Provides: report generation, multi-source research, MCP integration.
"""

import os
import asyncio
import logging
from typing import Dict, List, Optional
from datetime import datetime
from dataclasses import dataclass

logger = logging.getLogger(__name__)


class ResearchAgent:
    """Deep research agent (GPT Researcher style)."""

    def __init__(self):
        self.available = True
        self.max_sources = 5
        self.max_depth = 2

    async def research(self, query: str, depth: int = None) -> Dict:
        """Perform deep research on a topic."""
        depth = depth or self.max_depth

        try:
            # Search for sources
            sources = await self._search_sources(query, self.max_sources)

            # Extract information from each source
            findings = []
            for source in sources:
                content = await self._extract_content(source["url"])
                if content:
                    findings.append(
                        {
                            "source": source["url"],
                            "title": source.get("title", "Unknown"),
                            "content": content[:1000],
                        }
                    )

                # Limit to prevent too many requests
                if len(findings) >= depth * 2:
                    break

            # Generate summary (would use LLM in real implementation)
            summary = self._generate_summary(query, findings)

            return {
                "success": True,
                "query": query,
                "sources_count": len(sources),
                "findings": findings,
                "summary": summary,
                "timestamp": datetime.now().isoformat(),
            }

        except Exception as e:
            return {"success": False, "error": str(e), "query": query}

    async def _search_sources(self, query: str, limit: int) -> List[Dict]:
        """Search for relevant sources."""
        # Simple search using DuckDuckGo via browser agent
        try:
            from tools.browser_agent import get_browser_agent

            ba = get_browser_agent()
            result = await ba.search_web(query)

            if result.get("success") and result.get("results"):
                sources = []
                for i, title in enumerate(result["results"][:limit]):
                    sources.append(
                        {
                            "url": f"https://example.com/result_{i}",  # Would be real URLs
                            "title": title,
                            "rank": i + 1,
                        }
                    )
                return sources

        except Exception as e:
            logger.warning(f"Search failed: {e}")

        return []

    async def _extract_content(self, url: str) -> str:
        """Extract content from a URL."""
        try:
            from tools.browser_agent import get_browser_agent

            ba = get_browser_agent()
            result = await ba.extract_from_page(url, "Extract main content")

            if result.get("success"):
                return result.get("content", "")

        except Exception as e:
            logger.warning(f"Content extraction failed: {e}")

        return ""

    def _generate_summary(self, query: str, findings: List[Dict]) -> str:
        """Generate a summary from findings."""
        if not findings:
            return "No findings available."

        summary = f"Research on: {query}\n\n"
        summary += f"Found {len(findings)} sources.\n\n"

        for i, finding in enumerate(findings[:3], 1):
            summary += f"{i}. {finding.get('title', 'Unknown')}\n"

        summary += f"\nFull analysis would be generated by LLM."

        return summary

    async def generate_report(self, topic: str, format: str = "brief") -> Dict:
        """Generate a research report."""
        # Do research first
        research = await self.research(topic)

        if not research.get("success"):
            return research

        # Generate report based on format
        if format == "brief":
            report = self._brief_report(topic, research)
        elif format == "detailed":
            report = self._detailed_report(topic, research)
        else:
            report = research.get("summary", "No data")

        return {
            "success": True,
            "topic": topic,
            "format": format,
            "report": report,
            "sources": [f["source"] for f in research.get("findings", [])],
            "timestamp": datetime.now().isoformat(),
        }

    def _brief_report(self, topic: str, research: Dict) -> str:
        """Generate brief report."""
        return f"""
# Research: {topic}

## Summary
{research.get("summary", "No summary available.")}

## Sources
{len(research.get("findings", []))} sources found.

## Key Findings
"""

    def _detailed_report(self, topic: str, research: Dict) -> str:
        """Generate detailed report."""
        findings = research.get("findings", [])

        report = f"""
# Deep Research: {topic}

## Overview
This research was conducted on {datetime.now().strftime("%Y-%m-%d")}

## Sources Consulted
{len(findings)} sources were analyzed.

"""

        for i, f in enumerate(findings, 1):
            report += f"""
### Source {i}: {f.get("title", "Unknown")}
URL: {f.get("source", "N/A")}

{f.get("content", "No content extracted.")[:500]}

"""

        return report

    def get_status(self) -> Dict:
        """Get research agent status."""
        return {
            "available": self.available,
            "max_sources": self.max_sources,
            "max_depth": self.max_depth,
            "capabilities": [
                "research",
                "generate_report",
                "search_sources",
                "extract_content",
            ],
        }


# Singleton
_research_agent = None


def get_research_agent() -> ResearchAgent:
    global _research_agent
    if _research_agent is None:
        _research_agent = ResearchAgent()
    return _research_agent


# Test
if __name__ == "__main__":
    import asyncio

    async def test():
        ra = get_research_agent()

        print("🔬 Research Agent Status:")
        print(ra.get_status())

        print("\n🧪 Testing research:")
        result = await ra.research("artificial intelligence trends 2025")
        print(f"  Success: {result.get('success')}")
        print(f"  Sources: {result.get('sources_count', 0)}")

    asyncio.run(test())
